### PR TITLE
Update to v13

### PR DESCRIPTION
**Pull request by Dazeilad**
## Problem

- The app is outdated

## Solution

- I tried to understand how the version is chosen and made the little update that seemed necessary
- As the "main" version seems to be retrieved automatically, there is no auto upadte of the version number in the manifest.toml...

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Dazeilad** [comment]
!testme

**Comment by Dazeilad** [comment]
@ericgaspar @yalh76 I don't know if you are actually in charge of this package, but could you process this PR ? I tested it manually, the new version seems to work.
The only problem is that I don't know how to trigger the update for future versions automatically, as the source link in manifest.toml points to a meta V13 repo, without specifying the minor versions.

**Comment by ericgaspar** [comment]
!testme

**Comment by Dazeilad** [comment]
hmm the test timed out during the OpenProject configuration... Has the test server enough RAM ? This app is quite demanding...

**Comment by OniriCorpe** [comment]
!testme

**Comment by stepcellwolf** [comment]
HI, is there any chance that we have the latest version [OpenProject 13.4.1](https://www.openproject.org/docs/release-notes/13-4-1/)?
Or is it possible that I can initiated manually?

**Comment by stepcellwolf** [comment]
Maybe this workaround can be useful for others.
Manual update on Debian 11.
1. Add the repository to your distribution by this [guide](https://www.openproject.org/docs/installation-and-operations/installation/packaged/).
2. After `sudo apt update` run the next step
3. [Updating OpenProject](https://www.openproject.org/docs/installation-and-operations/operation/upgrading/#package-based-installation-debrpm) `sudo apt-get install --only-upgrade openproject`
4. Run `sudo openproject configure`

Check the logs and usually, everything should be fine. It worked for me successfully.

**Pull request closed without merging**
